import { NextRequest, NextResponse } from 'next/server';
import bcrypt from 'bcryptjs';
import { verifyOtp } from '@/lib/msg91';
import { createSignedSessionToken, verifySignedSessionToken } from '@/lib/auth';
import { checkRateLimit, getClientIp } from '@/lib/rate-limit';
import { logger } from '@/lib/logger';

/**
 * POST /api/otp/verify
 *
 * Verify OTP for application or parent login flows.
 * Uses MSG91 OTP API for verification.
 *
 * Request body:
 * - code: string - 6-digit OTP code
 * - token: string - Token from /api/otp/send response
 * - attempts: number - Number of verification attempts (client-side tracking)
 * - userAgent?: string - Browser user agent for logging
 *
 * Response:
 * - Success: 200 with { success: true, sessionToken: string }
 * - Error: 400/401 with { message: string }
 */
export async function POST(request: NextRequest) {
  try {
    // Rate limit: 5 verify attempts per 15 minutes per IP
    const ip = getClientIp(request);
    const rateLimit = checkRateLimit(`otp-verify:${ip}`, { maxRequests: 5, windowSeconds: 900 });
    if (!rateLimit.allowed) {
      return NextResponse.json(
        { message: `Too many verification attempts. Try again in ${rateLimit.retryAfterSeconds} seconds.` },
        { status: 429, headers: { 'Retry-After': String(rateLimit.retryAfterSeconds) } }
      );
    }

    const body = await request.json();
    const { code, token } = body;

    // Validate input
    if (!code) {
      return NextResponse.json(
        { message: 'OTP code is required' },
        { status: 400 }
      );
    }

    if (!token) {
      return NextResponse.json(
        { message: 'Token is required' },
        { status: 400 }
      );
    }

    // Validate OTP format
    if (!/^\d{4,6}$/.test(code)) {
      return NextResponse.json(
        { message: 'OTP must be a 4 to 6-digit number' },
        { status: 400 }
      );
    }

    // Decode token. Email OTPs use signed tokens (HMAC); SMS uses base64 JSON.
    let tokenData: any = verifySignedSessionToken(token);
    if (!tokenData) {
      try {
        const decoded = Buffer.from(token, 'base64').toString('utf-8');
        tokenData = JSON.parse(decoded);
      } catch {
        return NextResponse.json(
          { message: 'Invalid or expired token' },
          { status: 401 }
        );
      }
    }

    const contact = tokenData.contact;

    // Email and WhatsApp OTPs are generated by us and verified locally against
    // the bcrypt hash embedded in the signed token. SMS is verified by MSG91.
    if (
      (tokenData.channel === 'email' || tokenData.channel === 'whatsapp') &&
      tokenData.otpHash
    ) {
      const ok = await bcrypt.compare(code, tokenData.otpHash as string);
      if (!ok) {
        return NextResponse.json({ message: 'Invalid OTP code' }, { status: 401 });
      }
    } else {
      const msg91Result = await verifyOtp(contact, code);
      if (!msg91Result.success) {
        return NextResponse.json(
          { message: msg91Result.message || 'Invalid OTP code' },
          { status: 401 }
        );
      }
    }

    // Generate cryptographically signed session token with 30-minute expiry
    const sessionToken = createSignedSessionToken({
      contact: tokenData.contact,
      vertical: tokenData.vertical,
      verified: true,
    });

    // Determine redirect based on vertical
    const redirect = tokenData.vertical === 'parent'
      ? '/dashboard/parent'
      : `/apply/${tokenData.vertical}/form`;

    return NextResponse.json({
      success: true,
      sessionToken,
      message: 'OTP verified successfully',
      redirect
    });

  } catch (error: unknown) {
    const errMsg = error instanceof Error ? error.message : 'Unknown error';
    logger.error('OTP verify failed', { route: '/api/otp/verify', error: errMsg });
    return NextResponse.json(
      { message: 'Internal server error' },
      { status: 500 }
    );
  }
}
