/**
 * Twilio WhatsApp OTP sender.
 *
 * Unlike MSG91 (which owns OTP generation + verification), Twilio is used here
 * purely as a delivery transport: WE generate the OTP, hash it into a signed
 * session token, and verify locally — the same stateless pattern as the email
 * OTP path. This module only sends the code over WhatsApp via Twilio's
 * Messages API.
 *
 * Required env (production):
 *   TWILIO_ACCOUNT_SID            – Account SID from the Twilio console
 *   TWILIO_AUTH_TOKEN             – Auth token from the Twilio console
 *   TWILIO_WHATSAPP_FROM          – Sender, e.g. "whatsapp:+14155238886"
 *   TWILIO_WHATSAPP_OTP_CONTENT_SID – Approved authentication-template Content SID (HX...)
 *
 * In non-production, when credentials are absent the send is logged and
 * skipped so local development does not need a real Twilio account.
 *
 * @see https://www.twilio.com/docs/messaging/api/message-resource#create-a-message-resource
 */

import { logger } from './logger';
import { buildWhatsappOtp } from './otp-whatsapp';

const TWILIO_BASE_URL = 'https://api.twilio.com/2010-04-01';

interface TwilioConfig {
  accountSid: string;
  authToken: string;
  from: string;
  contentSid?: string;
}

function getConfig(): TwilioConfig | null {
  const accountSid = process.env.TWILIO_ACCOUNT_SID;
  const authToken = process.env.TWILIO_AUTH_TOKEN;
  const from = process.env.TWILIO_WHATSAPP_FROM;

  if (!accountSid || !authToken || !from) return null;

  return {
    accountSid,
    authToken,
    from: from.startsWith('whatsapp:') ? from : `whatsapp:${from}`,
    contentSid: process.env.TWILIO_WHATSAPP_OTP_CONTENT_SID,
  };
}

/**
 * Format a phone number to Twilio's `whatsapp:+E164` form.
 * Mirrors msg91.ts formatPhone for Indian numbers.
 */
function formatWhatsapp(phone: string): string {
  const cleaned = phone.replace(/[\s\-+]/g, '');

  let e164: string;
  if (cleaned.length === 12 && cleaned.startsWith('91')) {
    e164 = `+${cleaned}`;
  } else if (cleaned.length === 10 && /^[6-9]/.test(cleaned)) {
    e164 = `+91${cleaned}`;
  } else {
    e164 = phone.trim().startsWith('+') ? `+${cleaned}` : `+${cleaned}`;
  }

  return `whatsapp:${e164}`;
}

export interface WhatsappResult {
  success: boolean;
  skipped?: boolean;
  sid?: string;
  error?: string;
}

/**
 * Send a self-generated OTP over WhatsApp via Twilio.
 *
 * @param phone   - 10-digit Indian mobile number (or E.164)
 * @param otp     - The code generated by the caller
 * @param vertical - Application vertical, used for fallback message copy
 */
export async function sendWhatsappOtp(
  phone: string,
  otp: string,
  vertical: string
): Promise<WhatsappResult> {
  const config = getConfig();

  // Dev skip: log and succeed without dispatching when not configured.
  if (!config) {
    if (process.env.NODE_ENV !== 'production') {
      logger.info('Twilio WhatsApp: skipping send (dev or not configured)', { phone, vertical });
      return { success: true, skipped: true };
    }
    logger.error('Twilio WhatsApp: configuration missing in production');
    return { success: false, error: 'WhatsApp OTP is not configured' };
  }

  const { accountSid, authToken, from, contentSid } = config;
  const to = formatWhatsapp(phone);

  const params = new URLSearchParams();
  params.set('From', from);
  params.set('To', to);

  if (contentSid) {
    const { contentVariables } = buildWhatsappOtp(otp, vertical);
    params.set('ContentSid', contentSid);
    params.set('ContentVariables', JSON.stringify(contentVariables));
  } else {
    // No approved template configured — fall back to a plain-text body.
    // Outside Twilio's 24h session window WhatsApp will reject this, so this
    // path is intended for development / session-window testing only.
    const { body } = buildWhatsappOtp(otp, vertical);
    params.set('Body', body);
  }

  try {
    const auth = Buffer.from(`${accountSid}:${authToken}`).toString('base64');
    const response = await fetch(`${TWILIO_BASE_URL}/Accounts/${accountSid}/Messages.json`, {
      method: 'POST',
      headers: {
        Authorization: `Basic ${auth}`,
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: params.toString(),
    });

    const data = await response.json();

    if (!response.ok) {
      logger.error('Twilio WhatsApp: send failed', {
        status: response.status,
        code: data?.code,
        message: data?.message,
      });
      return { success: false, error: data?.message || 'Failed to send WhatsApp OTP' };
    }

    logger.info('Twilio WhatsApp: OTP sent', { to, sid: data?.sid });
    return { success: true, sid: data?.sid };
  } catch (error: unknown) {
    const errMsg = error instanceof Error ? error.message : 'Unknown error';
    logger.error('Twilio WhatsApp: request failed', { error: errMsg });
    return { success: false, error: `Twilio API error: ${errMsg}` };
  }
}
